spring:
  application:
    name: chess-backend
  datasource:
    url: jdbc:postgresql://localhost:55432/chess
    username: chess_local_user
    password: chess_local_pass
  flyway:
    clean-disabled: false
    clean-on-validation-error: true
    validate-migration-naming: true
